### ISSUE TITLE
gimy.tv can't play video, playlist showing fine (It was working three days ago)

### ISSUE THREAD

**Issue by popo2424** [ypchen/plugin.video.hdp_ims#2]
Hi Ypchen, I just want to say BIG thank you for this great kodi addon. I just found it 3 days ago and it was amazing :) You are my wife's lifesaver XD

Unfortunately, one day later, I found out most of the video links in gimy.tv now cannot be played. It just shows error. The playlist is working normally but just can't enter and play. KUBO is playing fine.

I saw another post of yours saying may be foreign IP issue? so I try to pc to watch gimy.tv and it is fine. Just wondering it is an issue on my end or anything else? If you can shine a light that will be much appreciated.

Thanks and regards,
Benson

**Comment by ypchen** [comment]
Hi Benson,

Frankly, I am glad to know that there are users. I didn't expect someone else would like to use this plug-in on their kodi system...

Since I myself am not a frequent user of this plug-in (actually, not frequently turning on TV), the glitches of it might just be found after a long time. Thank you for finding the issue.

I (think that I) have fixed the gimytv.com / gimy.tv issue this time... as you can see the gist modification, I added the following two lines:
gimytv_sources_str1 = '播放線路'
gimytv_sources_str8 = '播放線路'
to the latest quickfix gist, i.e., 1.18.3-gist-r4 ( https://gist.github.com/ypchen/a056ebf6ae5c46b2989a549f62702e3c ).

The cause is simply that gimytv modified their webpage...  from '播放地址' to '播放線路'. For the time being, the plug-in is working on my system. I hope this quickfix also works on your system. (Theoretically, you don't need to do anything. The plug-in will get the quickfix gist and use it.)

The foreign IP issue, if I remember correctly, existed only in aibuka/netstartv. (I guess) They ran (are running?) a video platform mainly for users in north America, and they allowed only non-Asian (or north America) IPs to access the video. As for as I know, kubo, gimytv, and gimycc seem just the opposite. Even Japan IPs are not allowed to access gimycc.

Anyway, please let me know if the quickfix resolved the issue you mentioned. Good luck and thank you.

Best,
ypchen

**Comment by ypchen** [comment]
Hi Benson,

I didn't notice that the foreign IP issue you mentioned is regarding kubotv... sorry, been a long time. :p

Best,
ypchen

**Comment by popo2424** [comment]
Hi ypchen,

Yes, it works like charm! Thank you so much. You have at least two families (me and my family) are using it in New Zealand :)

We have immigrated to NZ from TW long ago but my wife is relatively new in NZ, so she still into all kdrama and tw tv show. This is what I can find for her and my parents and they love it. So thank you so so so much.

We do not have foreign IP blockage issue, just I saw in another post under this trend not long ago.

Hope you have a great weekend. Much appreciated.

Benson

**Comment by ypchen** [comment]
Hi Benson,

It's good to know that the issue has been resolved (at least for the time being). Let's hope the owners of those website not to frequently make modifications breaking this plug-in. :)

I wish you and your family a great weekend, too.

Best,
ypchen
