### ISSUE TITLE
Can't install on Kodi 19.1

### ISSUE THREAD

**Issue by WhyredHuang** [ypchen/plugin.video.hdp_ims#3]
Tq, man for making this 

I am using android tv & install new kodi using playstore but this project into new kodi.

Plzz fix this problem

**Comment by ypchen** [comment]
Hi there. Thank you for reporting this issue. However, the problem is most likely caused by the adoption of Python 3 in Kodi v19. Before that, Kodi add-ons are written in Python 2. Since Python 2 and Python 3 are incompatible, all Kodi add-ons have to be re-written for Kodi v19.

As for now, I don't have either time or a plan to re-write this add-on. Hopefully I might have some time available to think about migrating this add-on to Kodi v19.

**Comment by WhyredHuang** [comment]
Tq man. i am already found solution (Downgrade to Kodi 18.9)

This Addon Work like a Charm.

**Comment by ypchen** [comment]
Sounds great. :)

(It's actually to my surprise that v19 starts to adopt Python 3. I thought they will never do that. :p)
